# Generated by Django 3.1.5 on 2021-02-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('sponsor', '0006_auto_20210123_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='organisers',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='title',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='events',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='events',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventDetails',
        ),
        migrations.DeleteModel(
            name='Organiser',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
