# Generated by Django 3.1.2 on 2021-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_auto_20210228_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
