# Generated by Django 3.1.2 on 2021-02-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20210228_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles_api.city'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles_api.city'),
        ),
    ]
