# Generated by Django 3.1.2 on 2021-03-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20210228_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsoredEvent',
        ),
    ]
